name: ideiaerp-sync

services:
  app-db:
    image: mariadb:10.11
    container_name: ideiaerp_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ideia
      MYSQL_DATABASE: ideiaerp
      MYSQL_USER: root
      MYSQL_PASSWORD: ideia
    ports:
      - "3307:3306"
    volumes:
      - app-db-data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - ideiaerp-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app-db-data:
    driver: local

networks:
  ideiaerp-network:
    driver: bridge

